// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfPidFdKey struct {
	Pid uint32
	Fd  int32
}

type bpfSocketEnterState struct {
	Family uint16
	Pad    uint16
}

type bpfSocketInfo struct {
	Family uint16
	Port   uint16
	Ip4    uint32
	Ip6    [16]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceEnterClone3  *ebpf.ProgramSpec `ebpf:"trace_enter_clone3"`
	TraceEnterConnect *ebpf.ProgramSpec `ebpf:"trace_enter_connect"`
	TraceEnterDup2    *ebpf.ProgramSpec `ebpf:"trace_enter_dup2"`
	TraceEnterDup3    *ebpf.ProgramSpec `ebpf:"trace_enter_dup3"`
	TraceEnterExecve  *ebpf.ProgramSpec `ebpf:"trace_enter_execve"`
	TraceEnterFork    *ebpf.ProgramSpec `ebpf:"trace_enter_fork"`
	TraceEnterPipe    *ebpf.ProgramSpec `ebpf:"trace_enter_pipe"`
	TraceEnterPipe2   *ebpf.ProgramSpec `ebpf:"trace_enter_pipe2"`
	TraceEnterSocket  *ebpf.ProgramSpec `ebpf:"trace_enter_socket"`
	TraceExitExecve   *ebpf.ProgramSpec `ebpf:"trace_exit_execve"`
	TraceExitSocket   *ebpf.ProgramSpec `ebpf:"trace_exit_socket"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	SocketEnterMap *ebpf.MapSpec `ebpf:"socket_enter_map"`
	SocketFdMap    *ebpf.MapSpec `ebpf:"socket_fd_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	SocketEnterMap *ebpf.Map `ebpf:"socket_enter_map"`
	SocketFdMap    *ebpf.Map `ebpf:"socket_fd_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.SocketEnterMap,
		m.SocketFdMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceEnterClone3  *ebpf.Program `ebpf:"trace_enter_clone3"`
	TraceEnterConnect *ebpf.Program `ebpf:"trace_enter_connect"`
	TraceEnterDup2    *ebpf.Program `ebpf:"trace_enter_dup2"`
	TraceEnterDup3    *ebpf.Program `ebpf:"trace_enter_dup3"`
	TraceEnterExecve  *ebpf.Program `ebpf:"trace_enter_execve"`
	TraceEnterFork    *ebpf.Program `ebpf:"trace_enter_fork"`
	TraceEnterPipe    *ebpf.Program `ebpf:"trace_enter_pipe"`
	TraceEnterPipe2   *ebpf.Program `ebpf:"trace_enter_pipe2"`
	TraceEnterSocket  *ebpf.Program `ebpf:"trace_enter_socket"`
	TraceExitExecve   *ebpf.Program `ebpf:"trace_exit_execve"`
	TraceExitSocket   *ebpf.Program `ebpf:"trace_exit_socket"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceEnterClone3,
		p.TraceEnterConnect,
		p.TraceEnterDup2,
		p.TraceEnterDup3,
		p.TraceEnterExecve,
		p.TraceEnterFork,
		p.TraceEnterPipe,
		p.TraceEnterPipe2,
		p.TraceEnterSocket,
		p.TraceExitExecve,
		p.TraceExitSocket,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
